### ISSUE TITLE
Face Tracking Improvements

### ISSUE THREAD

**Issue by TheBlueShift** [TheBlueShift/Faces#9]
- [x] Aggregate Data to reduce jittering
- [x] Separate Data from multiple Faces
- [x] Improve Scaling
- [x] Improve depth estimation
- [x] Track Multiple Faces
